// Auto-generated by MAZE
import java.lang.Exception;
import nl.uu.devtests.CtorTest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class CtorTestTest {
  @Test
  public void testTest1() throws Exception {
    int carg0 = 0;
    CtorTest cut = new CtorTest(carg0);

    boolean retval = cut.test();

    boolean expected = true;
    Assertions.assertEquals(expected, retval);
  }

  @Test
  public void testTest2() throws Exception {
    int carg0 = 5;
    CtorTest cut = new CtorTest(carg0);

    boolean retval = cut.test();

    boolean expected = false;
    Assertions.assertEquals(expected, retval);
  }
}
