// Auto-generated by MAZE
import java.lang.Exception;
import nl.uu.devtests.SetterTest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class SetterTestTest {
  @Test
  public void testSetI1() throws Exception {
    SetterTest cut = new SetterTest();

    int marg0 = 0;
    cut.setI(marg0);
  }

  @Test
  public void testTest1() throws Exception {
    SetterTest cut = new SetterTest();

    boolean retval = cut.test();

    boolean expected = true;
    Assertions.assertEquals(expected, retval);
  }
}
