// Auto-generated by MAZE
import java.lang.Exception;
import nl.uu.maze.examples.SimpleExample;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class SimpleExampleTest {
  @Test
  public void testFoobar1() throws Exception {
    SimpleExample cut = new SimpleExample();

    int marg0 = 0;
    int marg1 = 0;
    int retval = cut.foobar(marg0, marg1);

    int expected = 0;
    Assertions.assertEquals(expected, retval);
  }

  @Test
  public void testFoobar2() throws Exception {
    SimpleExample cut = new SimpleExample();

    int marg0 = 11;
    int marg1 = 0;
    int retval = cut.foobar(marg0, marg1);

    int expected = 11;
    Assertions.assertEquals(expected, retval);
  }

  @Test
  public void testFoobar3() throws Exception {
    SimpleExample cut = new SimpleExample();

    int marg0 = 11;
    int marg1 = 5;
    int retval = cut.foobar(marg0, marg1);

    int expected = 16;
    Assertions.assertEquals(expected, retval);
  }
}
